### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by peposso** [peposso/xlsxconverter#1]
[ ] json indent
[ ] show except location
[ ] djangofixture
[ ] csv
[ ] luafixture
[ ] multi threading
[ ] caching workbook
[ ] user friendly logging
[ ] range validator
[ ] multi workbooks
[ ] yaml inlined enum

**Comment by peposso** [comment]
- [ ] source code template engine (mustache?)
- [ ] fix string concating...
- [ ] cell position format like A1, AB12

**Comment by peposso** [comment]
- [ ] validate.sorted
- [ ] validate.sequential
- [ ] validate.max
- [ ] validate.min
- [ ] validate.anyof
